language: python

python:
  - "3.6"

before_script:
  - pip3 install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE="vegalt.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test

branches:
  only:
    - P11-add-contact-+-mail-features-+-test-fix